name: Pipeline

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Lint
        run: |
          yarn
          yarn lint
        env:
          CI: true
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Build
        run: |
          yarn
          yarn build
        env:
          CI: true

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        test-type: ["test", "test:environment", "test:advanced"]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: ${{ matrix.test-type }}
        run: |
          yarn
          yarn ${{ matrix.test-type }}
        env:
          CI: true

  publish:
    runs-on: ubuntu-latest

    needs: test

    if: startsWith(github.ref, 'v') && contains(github.ref, '.')
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          registry-url: "https://registry.npmjs.org"
      - name: Publish
        run: |
          yarn
          yarn publish --non-interactive
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
