name: Pipeline

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Lint
        run: |
          yarn --frozen-lockfile
          yarn lint
        env:
          CI: true
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Build
        run: |
          yarn --frozen-lockfile
          yarn build
        env:
          CI: true

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        test-type: ["test", "test:environment", "test:advanced"]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: ${{ matrix.test-type }}
        run: |
          yarn --frozen-lockfile
          yarn ${{ matrix.test-type }}
        env:
          CI: true

  publish:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          registry-url: "https://registry.npmjs.org"
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
